In [ ]:
#1. Create a pandas dataframe (dataframe ass df) with numpy random values (4 features and 4 observations)
import pandas as pd
import numpy as np
data = np.random.rand(4, 4)
df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'])
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.910759        0.583760        0.968668        0.065080
1        0.096815        0.814523        0.059784        0.308676
2        0.652457        0.065634        0.080036        0.812028
3        0.410038        0.358196        0.591761        0.407558

In [ ]:
#2. Rename the task -1 'df' dataframe column named as 'Random value 1', 'Random value 2','Random value 3','Random value 4'
df.rename(columns={'Random value 1': 'Feature 1', 'Random value 2': 'Feature 2', 'Random value 3': 'Feature 3', 'Random value 4': 'Feature 4'}, inplace=True)
df

   Feature 1  Feature 2  Feature 3  Feature 4
0   0.910759   0.583760   0.968668   0.065080
1   0.096815   0.814523   0.059784   0.308676
2   0.652457   0.065634   0.080036   0.812028
3   0.410038   0.358196   0.591761   0.407558

In [ ]:
#3.  Find the descriptive statistics of the 'df' dataframe
statistics = df.describe()
statistics

       Feature 1  Feature 2  Feature 3  Feature 4
count   4.000000   4.000000   4.000000   4.000000
mean    0.517517   0.455528   0.425062   0.398335
std     0.347078   0.319798   0.438089   0.311087
min     0.096815   0.065634   0.059784   0.065080
25%     0.331733   0.285056   0.074973   0.247777
50%     0.531248   0.470978   0.335898   0.358117
75%     0.717033   0.641451   0.685988   0.508675
max     0.910759   0.814523   0.968668   0.812028

In [ ]:
#4. Check for the null values in 'df' and  find the data type of the columns.
null_values = df.isnull().sum()
data_types = df.dtypes
null_values
data_types

Feature 1    float64
Feature 2    float64
Feature 3    float64
Feature 4    float64
dtype: object

In [ ]:
#5. Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.
random_value_2_loc = df.loc[:, 'Feature 2']
random_value_3_loc = df.loc[:, 'Feature 3']

random_value_2_idx = df.iloc[:, 1]
random_value_3_idx = df.iloc[:, 2]

random_value_2_loc
random_value_3_loc
random_value_2_idx
random_value_3_idx

0    0.968668
1    0.059784
2    0.080036
3    0.591761
Name: Feature 3, dtype: float64

In [ ]:
#Task-1: Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)
import pandas as pd
import numpy as np
data = np.random.rand(10, 5)
df = pd.DataFrame(data, columns=['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4', 'Feature 5'])
df

   Feature 1  Feature 2  Feature 3  Feature 4  Feature 5
0   0.332669   0.649496   0.308702   0.321375   0.001881
1   0.043745   0.836487   0.536459   0.108012   0.237719
2   0.535087   0.767812   0.641883   0.492268   0.000455
3   0.702773   0.162389   0.822479   0.116510   0.306344
4   0.341773   0.868904   0.943819   0.321664   0.882667
5   0.344263   0.954120   0.156024   0.156480   0.113806
6   0.172633   0.656290   0.313350   0.884553   0.797069
7   0.853232   0.882275   0.579258   0.328026   0.793526
8   0.448658   0.884896   0.432874   0.901803   0.877660
9   0.240664   0.774705   0.768285   0.952969   0.754800

In [ ]:
#Task- 2 Check the info of 'df'
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Feature 1  10 non-null     float64
 1   Feature 2  10 non-null     float64
 2   Feature 3  10 non-null     float64
 3   Feature 4  10 non-null     float64
 4   Feature 5  10 non-null     float64
dtypes: float64(5)
memory usage: 528.0 bytes

In [ ]:
#Task 3- Check the descriptive statistics of 'df'
df.describe()

       Feature 1  Feature 2  Feature 3  Feature 4  Feature 5
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.401550   0.743737   0.550313   0.458366   0.476593
std     0.243291   0.226981   0.251580   0.334870   0.376537
min     0.043745   0.162389   0.156024   0.108012   0.000455
25%     0.263665   0.684171   0.343231   0.197704   0.144784
50%     0.343018   0.805596   0.557859   0.324845   0.530572
75%     0.513480   0.878932   0.736685   0.786482   0.796183
max     0.853232   0.954120   0.943819   0.952969   0.882667

In [ ]:
#Task 4- check the 4th index observation with 'loc' slicing operator.
observation_4 = df.loc[4]
observation_4

Feature 1    0.341773
Feature 2    0.868904
Feature 3    0.943819
Feature 4    0.321664
Feature 5    0.882667
Name: 4, dtype: float64

In [ ]:
#Task 5 - Check the null values in your 'df'
null_values = df.isnull().sum()
null_values

Feature 1    0
Feature 2    0
Feature 3    0
Feature 4    0
Feature 5    0
dtype: int64